# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marsh/Networks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marsh/Networks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marsh/Networks/CMakeFiles /home/marsh/Networks//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marsh/Networks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

#=============================================================================
# Target rules for targets named test_client

# Build rule for target.
test_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_client
.PHONY : test_client

# fast build rule for target.
test_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/build
.PHONY : test_client/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

src/cfg/sock_config.o: src/cfg/sock_config.c.o
.PHONY : src/cfg/sock_config.o

# target to build an object file
src/cfg/sock_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/cfg/sock_config.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cfg/sock_config.c.o
.PHONY : src/cfg/sock_config.c.o

src/cfg/sock_config.i: src/cfg/sock_config.c.i
.PHONY : src/cfg/sock_config.i

# target to preprocess a source file
src/cfg/sock_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/cfg/sock_config.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cfg/sock_config.c.i
.PHONY : src/cfg/sock_config.c.i

src/cfg/sock_config.s: src/cfg/sock_config.c.s
.PHONY : src/cfg/sock_config.s

# target to generate assembly for a file
src/cfg/sock_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/cfg/sock_config.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cfg/sock_config.c.s
.PHONY : src/cfg/sock_config.c.s

src/cfg/support.o: src/cfg/support.c.o
.PHONY : src/cfg/support.o

# target to build an object file
src/cfg/support.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/cfg/support.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src/cfg/support.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cfg/support.c.o
.PHONY : src/cfg/support.c.o

src/cfg/support.i: src/cfg/support.c.i
.PHONY : src/cfg/support.i

# target to preprocess a source file
src/cfg/support.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/cfg/support.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src/cfg/support.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cfg/support.c.i
.PHONY : src/cfg/support.c.i

src/cfg/support.s: src/cfg/support.c.s
.PHONY : src/cfg/support.s

# target to generate assembly for a file
src/cfg/support.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/cfg/support.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src/cfg/support.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cfg/support.c.s
.PHONY : src/cfg/support.c.s

src/cfg/threads_config.o: src/cfg/threads_config.c.o
.PHONY : src/cfg/threads_config.o

# target to build an object file
src/cfg/threads_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/cfg/threads_config.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cfg/threads_config.c.o
.PHONY : src/cfg/threads_config.c.o

src/cfg/threads_config.i: src/cfg/threads_config.c.i
.PHONY : src/cfg/threads_config.i

# target to preprocess a source file
src/cfg/threads_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/cfg/threads_config.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cfg/threads_config.c.i
.PHONY : src/cfg/threads_config.c.i

src/cfg/threads_config.s: src/cfg/threads_config.c.s
.PHONY : src/cfg/threads_config.s

# target to generate assembly for a file
src/cfg/threads_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/cfg/threads_config.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/cfg/threads_config.c.s
.PHONY : src/cfg/threads_config.c.s

src/client/client.o: src/client/client.c.o
.PHONY : src/client/client.o

# target to build an object file
src/client/client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.c.o
.PHONY : src/client/client.c.o

src/client/client.i: src/client/client.c.i
.PHONY : src/client/client.i

# target to preprocess a source file
src/client/client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.c.i
.PHONY : src/client/client.c.i

src/client/client.s: src/client/client.c.s
.PHONY : src/client/client.s

# target to generate assembly for a file
src/client/client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/client.c.s
.PHONY : src/client/client.c.s

src/server/server.o: src/server/server.c.o
.PHONY : src/server/server.o

# target to build an object file
src/server/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.c.o
.PHONY : src/server/server.c.o

src/server/server.i: src/server/server.c.i
.PHONY : src/server/server.i

# target to preprocess a source file
src/server/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.c.i
.PHONY : src/server/server.c.i

src/server/server.s: src/server/server.c.s
.PHONY : src/server/server.s

# target to generate assembly for a file
src/server/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server/server.c.s
.PHONY : src/server/server.c.s

src/test_client/test_client.o: src/test_client/test_client.c.o
.PHONY : src/test_client/test_client.o

# target to build an object file
src/test_client/test_client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src/test_client/test_client.c.o
.PHONY : src/test_client/test_client.c.o

src/test_client/test_client.i: src/test_client/test_client.c.i
.PHONY : src/test_client/test_client.i

# target to preprocess a source file
src/test_client/test_client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src/test_client/test_client.c.i
.PHONY : src/test_client/test_client.c.i

src/test_client/test_client.s: src/test_client/test_client.c.s
.PHONY : src/test_client/test_client.s

# target to generate assembly for a file
src/test_client/test_client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_client.dir/build.make CMakeFiles/test_client.dir/src/test_client/test_client.c.s
.PHONY : src/test_client/test_client.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... client"
	@echo "... server"
	@echo "... test_client"
	@echo "... src/cfg/sock_config.o"
	@echo "... src/cfg/sock_config.i"
	@echo "... src/cfg/sock_config.s"
	@echo "... src/cfg/support.o"
	@echo "... src/cfg/support.i"
	@echo "... src/cfg/support.s"
	@echo "... src/cfg/threads_config.o"
	@echo "... src/cfg/threads_config.i"
	@echo "... src/cfg/threads_config.s"
	@echo "... src/client/client.o"
	@echo "... src/client/client.i"
	@echo "... src/client/client.s"
	@echo "... src/server/server.o"
	@echo "... src/server/server.i"
	@echo "... src/server/server.s"
	@echo "... src/test_client/test_client.o"
	@echo "... src/test_client/test_client.i"
	@echo "... src/test_client/test_client.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

